### ISSUE TITLE
Electricity Billing System should be Web Based Application

### ISSUE THREAD

**Issue by Kamlesh780** [kunaltyagi9/Electricity-Billing-System#4]
This is a desktop application. 
- How the changes made by the customers will be visible to the admin and vice versa? 
- Since it's a Desktop Based Application, how the action performed by the customer will be reflected in the admin's database?

**Comment by kunaltyagi9** [comment]
You can create a centralized MySQL Database on AWS and you can update all the changes there. That will resolve both of your queries. And Every type of application has its own use. There is no point arguing that is should be a web based application

**Comment by Kamlesh780** [comment]
> You can create a centralized MySQL Database on AWS and you can update all the changes there. That will resolve both of your queries. And Every type of application has its own use. There is no point arguing that is should be a web based application

Thank you for your positive reply. I was also thinking the same :)
