### ISSUE TITLE
Issue related to project

### ISSUE THREAD

**Issue by Sahil-Mukund-Jadhav** [kunaltyagi9/Electricity-Billing-System#5]
This is a desktop application.

How the changes made by the customer s will be visible to the admin and vice versa?
Since it's a Desktop Based Application, how the action performed by the customer will be reflected in the admin's database?

**Comment by kunaltyagi9** [comment]
You can create a centralized MySQL Database on AWS and you can update all the changes there. That will resolve both of your queries
